 version: '3'
 services:
  frontend:
    image: frontend:1.1
    build:
      context: ./frontend/
    ports:
      - "3000:5000"
  basckend:
    image: backend:1.1
    build:
      context: ./backend/
    ports:
      - "3001:5000"

    

