 version: '3'
 services:
  frontend:
    image: frontend:1.0
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
  basckend:
    image: backend:1.0
    build:
      context: ./backend/
    ports:
      - "3001:3001"

    

