version: '3'
services:
  frontend:
    image: frontend:1.4
    build:
      context: ./frontend/
    ports:
      - "3002:3002"

  backend:
    image: backend:1.4
    build:
      context: ./backend/
    environment:
      - DATABASE_URL=mongodb+srv://amarnadagera01:tbERyf7jKVCeCwpV@cluster0.t3nrpbk.mongodb.net/nodejs?retryWrites=true&w=majority
    depends_on:
      - mongo
    ports:
      - "3001:5000"
  mongo:
    image: mongo:5
    name: database:1.0
    hostname: nodejs
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amarnadagera01
      - MONGO_INITDB_ROOT_PASSWORD=tbERyf7jKVCeCwpV
    ports:
      - "27017:27017"
